- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- NOTICE.md
- README.md
- SECURITY.md
Update:
- README.md
Add:
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- NOTICE.md
- SECURITY.md
- 
> doc: Update README.md and add legal documents

- scripts/macosx-notarize.sh
This reverts commit fa7ca212f93721f731d5e1e2a00b80b2d7c740ad.
> Revert "Debug macosx-notarize.sh OOMKilled failures"

- jenkins/pipelines/tracecompass-test.Jenkinsfile
> Fix notarization step for tracecompass-test.Jenkinsfile

- jenkins/pipelines/tracecompass-sonar.Jenkinsfile
- jenkins/pod-templates/tracecompass-test-pod.yaml
Testing new build image before applying it to main Jenkinsfiles.
> Update test pod for ubuntu 22-04 image and apply to sonar job

- jenkins/pipelines/tracecompass-test.Jenkinsfile
> Test new dockerimage

- jenkins/pod-templates/tracecompass-test-pod.yaml
> Increase memory for test pod (for sonar testing)

- jenkins/pod-templates/tracecompass-test-pod.yaml
> Fix tracecompass-test-pod.yaml memory allocation

- jenkins/pipelines/tracecompass-sonar.Jenkinsfile
- jenkins/pod-templates/tracecompass-sonar-pod.yaml
Copy over configuration after successful sonar build from:
tracecompass-sonar.Jenkinsfile
tracecompass-test-pod.yaml
> Update tracecompass-sonar-pod.yaml for successful build with test files

- jenkins/pipelines/tracecompass-test.Jenkinsfile
This is to test incubator build after fixing Python configuration in docker image tracecompass-build-env:22.04.
> Configure tracecompass-test.Jenkinsfile for incubator build

- jenkins/pipelines/tracecompass-jdk17.Jenkinsfile
> Fix typo in tracecompass-jdk17.pod.Jenkinsfile

- jenkins/pipelines/tracecompass-test.Jenkinsfile
> Update test for trace compass including credentials for checkout

- jenkins/pipelines/tracecompass-jdk17.Jenkinsfile
> Fix pod filename in tracecompass-jdk17.Jenkinsfile

- jenkins/pipelines/tracecompass-jdk17.Jenkinsfile
This change should be applied to all active branches.
> Reduce disk usage

- jenkins/pipelines/tracecompass-incubator-jdk17.Jenkinsfile
- jenkins/pipelines/tracecompass-jdk17-mvn38.Jenkinsfile
- jenkins/pipelines/tracecompass-sonar.Jenkinsfile
- jenkins/pipelines/tracecompass-test.Jenkinsfile
> Reduce disk usage in all Jenkinfiles

- jenkins/pipelines/tracecompass-test.Jenkinsfile
I hope this will be enough for the generator to run as expected.
> test Jenkinsfile: add doublequotes around RCP_TITLE

- jenkins/pipelines/tracecompass-incubator-jdk17.Jenkinsfile
- jenkins/pipelines/tracecompass-jdk17-mvn38.Jenkinsfile
- jenkins/pipelines/tracecompass-jdk17.Jenkinsfile
- jenkins/pipelines/tracecompass-sonar.Jenkinsfile
- jenkins/pipelines/tracecompass-test.Jenkinsfile
Add `extensions: [[$class: 'CleanCheckout']],` to checkout step
> Fix build by adding CleanCheckout extension for checkout step

- jenkins/pipelines/tracecompass-incubator-jdk17.Jenkinsfile
> Test checkout checkout step

- jenkins/pipelines/tracecompass-incubator-jdk17.Jenkinsfile
> Debug jenkins file

- jenkins/pipelines/tracecompass-incubator-jdk17.Jenkinsfile
- jenkins/pipelines/tracecompass-jdk17-mvn38.Jenkinsfile
- jenkins/pipelines/tracecompass-jdk17.Jenkinsfile
- jenkins/pipelines/tracecompass-sonar.Jenkinsfile
- jenkins/pipelines/tracecompass-test.Jenkinsfile
> Remove refspec from userRemoteConfigs after removing gerrit trigger

- jenkins/pipelines/tracecompass-jdk17.Jenkinsfile
- jenkins/pipelines/tracecompass-test.Jenkinsfile
- scripts/generate_download_page.sh
It's now aligned with the test jenkinsfile.
When using the Jenkinsfile from a job, set job parameter "WEBPAGE_TITLE" to customize the download page title (default: "Download Page").
> tracecompass-jdk17.Jenkinsfile: use download page generator
